[package]
name = "event-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.8.17", features = ["csr"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
wasm-bindgen = "0.2.114"
js-sys = "0.3.91"
web-sys = { version = "0.3.83", features = [
    "Window", "Storage",
    "Blob", "Url",
    "Document", "HtmlElement",
    "HtmlAnchorElement", "HtmlInputElement",
    "FileReader", "File", "FileList",
    "TouchEvent", "Touch", "TouchList",
] }
console_error_panic_hook = "0.1.7"
rexie = "0.5"
serde-wasm-bindgen = "0.6"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
