[package]
name = "tech-event-announce"
version = "0.1.0"
edition = "2024"

[lib]
name = "techeventannouncelib"
crate-type = ["rlib"]

[[bin]]
name = "tech-event-announce"
path = "src/main.rs"

[dependencies]
leptos = { version = "0.8.19", features = ["csr"] }
wasm-bindgen = "0.2.114"
js-sys = "0.3.91"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3.83", features = [
    "Window",
    "Navigator",
    "Clipboard",
    "HtmlInputElement",
    "HtmlTextAreaElement",
] }
console_error_panic_hook = "0.1.7"

[dev-dependencies]
wasm-bindgen-test = "0.3"
